game.RunService.Heartbeat:Connect(function()
    coroutine.wrap(function()
        -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
    
    local ohTable1 = {
        ["Character"] = workspace.synolope,
        ["CFrame"] = CFrame.new(999,999,999),
        ["IsRunning"] = true
    }
    
    game:GetService("ReplicatedStorage").Knit.Services.CharacterService.RE.UpdateCharacterState:FireServer(ohTable1)
    
    -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
    
    local ohTable1 = {
        ["Character"] = workspace.synolope,
        ["CFrame"] = CFrame.new(0,0,0),
        ["IsRunning"] = true
    }
    
    game:GetService("ReplicatedStorage").Knit.Services.CharacterService.RE.UpdateCharacterState:FireServer(ohTable1)
    end)()
    end)

while wait(2) do
    for _,obj in pairs(workspace.Map.Objects:GetChildren()) do
        if obj.ClassName == "Model" then
            coroutine.wrap(function()
                local ohString1 = obj.Name
    
                game:GetService("ReplicatedStorage").Knit.Services.WorldCurrencyService.RE.PickupCurrency:FireServer(ohString1)
                obj:Destroy()
            end)()
        end
    end
end